version: '3.7'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: food_stock_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5404:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - foodstock_network

  backend:
    build:
      context: .
      dockerfile: src/FoodStock.Api/Dockerfile      
    container_name: food_stock_backend
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - connectionString=Host=food_stock_database;Port=5432;Database=FoodStock;Username=postgres;Password=admin;Include Error Detail=true
    depends_on:
      - postgres
    networks:
      - foodstock_network

networks:
  foodstock_network:    

volumes:
  postgres:
    driver: local