version: '3.4'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: food_stock_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin    
    ports:
      - 5404:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local